var workordertables=[	{type:0,cells:[{type:"text",attr:"f1_id"}]},
						{type:2,rowNum:1,cells:[
								
									{type:"lbl",text:"地点",width:80,align:"center",row:1},
									{type:"lbl",text:"化德风电",width:200,align:"left",row:1},
									{type:"lbl",text:"状态",width:80,align:"center",row:1},
									{type:"txt",attr:"status_name",width:400,align:"center",row:1}
						]},
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"设备编码",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_assetnum",width:200,align:"left",row:1,lov:"asset",onchange:shebei_change},
									{type:"lbl",text:"设备名称",width:80,align:"center",row:1},
									{type:"txt",attr:"asset_name",width:400,align:"center",row:1}
						]},
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"编号",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_code",width:200,align:"left",row:1},
									{type:"lbl",text:"部门单位",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_dept",width:400,align:"left",row:1}
									
						]},
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"1、",width:40,align:"center",row:1},
									{type:"lbl",text:"工作负责人",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_per_fzr_name",attr2:"f1_per_fzr",width:160,align:"left",row:1,lov:"stuff"},
									{type:"lbl",text:"工段（班组）名称",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_class_name",attr2:"f1_class",width:360,align:"left",row:1,lov:"workClassGet"}
						]},
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"2、",width:40,align:"center",row:1},
									{type:"lbl",text:"工作班成员",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_member",width:360,align:"left",row:1},
									{type:"lbl",text:"工作班人数",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_mem_num",width:160,align:"left",row:1}
						]},
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"3、",width:40,align:"center",row:1},
									{type:"lbl",text:"设备双重名称",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_sc_name",width:640,align:"left",row:1}
						]},
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"4、",width:40,align:"center",row:1},
									{type:"lbl",text:"工作地点",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_location",width:640,align:"left",row:1}
						]},
						
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"",width:40,align:"center",row:1},
									{type:"lbl",text:"工作内容",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_content",width:640,align:"left",row:1}
						]},
						
						{type:2,rowNum:1,cells:[
									{type:"lbl",text:"5、",width:40,align:"center",row:1},
									{type:"lbl",text:"计划工作开始时间",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_jhstart",width:240,align:"left",row:1,lov:"datetime"},
									{type:"lbl",text:"计划工作结束时间",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_jhfinish",width:240,align:"left",row:1,lov:"datetime"}
						]},
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"6、",width:40,align:"center",row:1},
									{type:"lbl",text:"工作条件",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_condition",width:640,align:"left",row:1}
						]},		
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"7、",width:40,align:"center",row:1},
									{type:"lbl",text:"安全措施",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_safety",width:640,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"工作票签发人",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_qfr_name",width:120,align:"left",row:1},
									{type:"lbl",text:"工作票签发时间",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_tm_qfr",width:160,align:"left",row:1,lov:"datetime"},
									{type:"lbl",text:"值长签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_zz_sp",width:120,align:"left",row:1}
						]},	
						
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"8、",width:40,align:"center",row:1},
									{type:"lbl",text:"补充安全措施",width:80,align:"center",row:1},
									{type:"txt",attr:"f1_safety_bc",width:640,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"9、",width:40,align:"center",row:1},
						            {type:"lbl",text:"确认本工作票1至8项：许可开始工作时间",width:240,align:"center",row:1},
									{type:"txt",attr:"f1_tm_xk",width:480,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"",width:40,align:"center",row:1},
						            {type:"lbl",text:"工作负责人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_fzr_xk",width:240,align:"left",row:1},
									{type:"lbl",text:"工作许可人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_xkr_xk_name",width:240,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"10、",width:40,align:"center",row:1},
						            {type:"lbl",text:"&nbsp;&nbsp;确认工作负责人布置的任务和本施工项目安全措施",width:720,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"",width:40,align:"center",row:1},
									{type:"lbl",text:"工作班成员签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_class_mem",width:600,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"11、",width:40,align:"center",row:1},
						            {type:"lbl",text:"工作票延期：有效期延长到",width:240,align:"center",row:1},
									{type:"txt",attr:"f1_tm_yq",width:480,align:"left",row:1,lov:"datatime"}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"",width:40,align:"center",row:1},
						            {type:"lbl",text:"工作负责人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_fzr_yq",width:240,align:"left",row:1},
									{type:"lbl",text:"工作许可人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_xkr_yq",width:240,align:"left",row:1}
						]},
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"12、",width:40,align:"center",row:1},
						            {type:"lbl",text:"检修交待",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_jxjd",width:600,height:120,align:"left",row:1}
						]},
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"13、",width:40,align:"center",row:1},
						            {type:"lbl",text:"&nbsp;&nbsp;&nbsp;&nbsp;工作终结：&nbsp;&nbsp;&nbsp;&nbsp;全部工作于",width:200,align:"left",row:1},
									{type:"txt",attr:"f1_actfinish",width:160,align:"left",row:1,lov:"datetime"},
									{type:"lbl",text:"&nbsp;&nbsp;&nbsp;&nbsp;结束，工作人员已全部撤离，材料工具已清理完毕。",width:360,align:"left",row:1}
						]},
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"工作负责人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_fzr_js_name",width:120,align:"left",row:1},
									{type:"lbl",text:"工作许可人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_xkr_js",width:120,align:"left",row:1},
									{type:"lbl",text:"工作票终结时间",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_tm_zj",width:160,align:"left",row:1,lov:"datetime"}
						]},	           
					    {type:2,rowNum:1,cells:[
						            {type:"lbl",text:"14、",width:40,align:"center",row:1},
									{type:"lbl",text:"备&nbsp;&nbsp注",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_qtsx",width:600,align:"left",row:1}
						]},	
						{type:2,rowNum:1,cells:[
						            {type:"lbl",text:"",width:40,align:"center",row:1},
									{type:"lbl",text:"备注人签名",width:120,align:"center",row:1},
									{type:"txt",attr:"f1_per_jhr_zj",width:600,align:"left",row:1}
						]}
							
					];